### PR TITLE
Use RequestSite instead of get_current_site - PMT #104925

### PR DESCRIPTION
**Pull request by nikolas**
RequestSite looks at the domain to determine which site we are on, which
is how care-cdm.ccnmtl and care-ssw.ccnmtl are set up.

https://docs.djangoproject.com/en/1.9/ref/contrib/sites/#requestsite-objects

### CODE REVIEW

**Comment by sdreher** [comment]
another Site.objects.get_current reference. you'll have to pass the request in from the calling functions.:  https://github.com/ccnmtl/carr/blob/use-requestsite/carr/quiz/scores.py#L210

**Comment by nikolas** [comment]
Thanks, I will replace these remaining references to `Site` objects. I should have caught those.

**Comment by nikolas** [comment]
Okay, I've updated `scores.py` to use RequestSite in get_student_info. There are also references to `Site.objects.get_current()` in activity_bruise_recon/models.py and carr/activity_taking_action/models.py, but it's less obvious how to pass in the request param here.

**Comment by sdreher** [comment]
Would a middleware shim that sets SITE_ID based on host be a solution?

**Comment by nikolas** [comment]
Yeah, I think that would work. And then in Block.site() we can do something like `return Site.objects.get(id=settings.SITE_ID)`

**Comment by nikolas** [comment]
Or maybe that's not even necessary if get_current() already looks at the SITE_ID

**Comment by sdreher** [comment]
I think the rest of the code would not need to change at all. And, that's a good thing as there's some other magic going on that relies on having a real Site object.

**Comment by nikolas** [comment]
I opened a new branch/PR for the site id middleware

**Comment by nikolas** [comment]
closing this PR since the middleware seems to take care of all the problems we've seen so far

**Pull request closed without merging**
